Ext.define('AM.view.transport.List', {
    extend:'Ext.grid.Panel',
    alias:'widget.transportlist',
    store:'Transports',

    dockedItems:[
        {
            xtype:'toolbar',
            items:[
                {
                    iconCls:'icon-add',
                    itemId:'J_TransportAdd',
                    text:'新增',
                    scope:this
                },
                '-',
                {
                    iconCls:'icon-edit',
                    itemId:'J_TransportEdit',
                    text:'编辑',
                    disabled:true,
                    scope:this
                },
                '-',
                {
                    iconCls:'icon-delete',
                    itemId:'J_TransportDelete',
                    text:'删除',
                    scope:this,
                    disabled:true
                }
            ]
        }
    ]
});